// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/greet/[name].tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/button.tsx";
import * as $$2 from "./islands/dialog.tsx";
import * as $$3 from "./islands/input.tsx";
import * as $$4 from "./islands/phone.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/greet/[name].tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/button.tsx": $$1,
    "./islands/dialog.tsx": $$2,
    "./islands/input.tsx": $$3,
    "./islands/phone.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
